webauthn4j/webauthn4j

- README.md
> Fix artifactId in README.md

- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationObject.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/packed/PackedAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/attestation/packed/PackedAttestationStatementValidatorTest.java
If the signature is valid an Validation exception is thrown. 
I added some tests in order to verify if everything went wel.
> Fixing signature validation on AttestationStatements

- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnRegistrationContextValidator.java
> Expose exceptions in the signature of popular public methods

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifier.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/jws/JWAIdentifier.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifierTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/jws/JWAIdentifierTest.java
Removed the switch statements in the Algorithm-enums "create" methods in favor of streams.
> Removed switch statement in favor of streams for the create-method.

- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/AbstractStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidkey/AndroidKeyAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidkey/NullAndroidKeyAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/AndroidSafetyNetAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/NullAndroidSafetyNetAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/none/NoneAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/packed/NullPackedAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/NullTPMAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/u2f/FIDOU2FAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/u2f/NullFIDOU2FAttestationStatementValidator.java
Moved the "supports" method to a abstract class
> Generified AttestationStatementValidators

- build.gradle
- gradle.properties
Added owasp dependency check task to scan for known CVEs
> Added owasp dependency check task to scan for known CVEs

- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidatorTest.java
#80 by Kris plus some refactoring
> Bugfix for TPMAttestationValidator validateSubjectAlternativeName NPE

- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/u2f/FIDOU2FAttestationStatementValidatorTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/KeyUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestAttestationUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/u2f/FIDOU2FAuthenticator.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnModelAuthenticator.java
- webauthn4j-util/build.gradle
- webauthn4j-util/src/test/java/com/webauthn4j/util/KeyUtilTest.java
* Move `KeyUtil` from `util` module to `test` module
* make `KeyUtil` `secureRandom` field final
> Move KeyUtil from util module to test module

- webauthn4j-core/src/main/java/com/webauthn4j/validator/ExtensionValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/ExtensionValidatorTest.java
If expectedExtensionIdentifiers are null, skip extension Id validation
> Relax extension id validation

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/FidoMdsMetadataItemsProvider.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/JsonFileMetadataStatementsProvider.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/exception/UnknownProtocolFamilyException.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/validator/MetadataItemValidator.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/validator/MetadataStatementValidator.java
- webauthn4j-metadata/src/test/java/com/webauthn4j/metadata/JsonFileMetadataStatementsProviderTest.java
> Add metadata statement validation

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorImplTest.java
> Add extensions to Authenticator interface

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifier.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/ESSignatureAlgorithmTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifierTest.java
as current implementation doesn't accept non-predefined
COSEAlgorithmIndentifier.
> Change COSEAlgorithmIdentifier type from enum to class

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorTransport.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticatorTransportConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorTransportTest.java
Address https://github.com/w3c/webauthn/issues/1268
> Change AuthenticatorTransport type from enum to class

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/RSACOSEKeySerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AbstractCOSEKey.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/COSEKey.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/EC2COSEKey.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/RSACOSEKey.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AssertionSignatureValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/u2f/FIDOU2FAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/EC2COSEKeyTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/RSACOSEKeyTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestDataUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnModelAuthenticator.java
https://github.com/webauthn4j/webauthn4j/pull/129
> Rework CredentialPublicKey design (cont.)

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
Addresses https://github.com/webauthn4j/webauthn4j/issues/143
> Remove unnessesary setters

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorTransport.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorTransportTest.java
> Add INTERNAL constant to AuthenticatorTransport

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
Addresses https://github.com/webauthn4j/webauthn4j/issues/141
Continue to https://github.com/webauthn4j/webauthn4j/pull/144
> Make default methods

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
- Update equals and hashCode methods of AuthenticatorImpl
> Bugfix: AuthenticatorImpl equals and hashCode methods don't reflect extensions members

- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationObject.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticationObjectTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/CustomAuthenticationValidatorTest.java
Pass `Authenticator` instance to `CustomAuthenticationValidator`  through `AuthenticatorObject`
> Pass Authenticator instance to CustomAuthenticationValidator 

- docs/src/reference/asciidoc/en/known-issues.adoc
- docs/src/reference/asciidoc/ja/known-issues.adoc
> Update known issues

- owasp/suppression.xml
> Suppress Jackson CVE as it doesn't affect webauthn4j

- webauthn4j-core/src/main/java/com/webauthn4j/anchor/KeyStoreFileTrustAnchorsProvider.java
- webauthn4j-core/src/test/java/com/webauthn4j/anchor/CertFileTrustAnchorsProviderTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/anchor/KeyStoreFileTrustAnchorsProviderTest.java
> Bugfix: KeyStoreFileTrustStoreProvider must return AAGUID.NULL key map

- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
Before working on #160, clarify spec correspondence in assertion verification.
> Clarify spec correspondence in assertion verification

- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java
Cont. to #168 
- Swap step 12 and 13 in authentication assertion
> Improve assertion verification conformance

- webauthn4j-core/src/main/java/com/webauthn4j/data/WebAuthnAuthenticationContext.java
- webauthn4j-core/src/test/java/com/webauthn4j/WebAuthnAuthenticationContextTest.java
Cont. to #171 
To work on #160, WebAuthnAuthenticationContext needs to have userHandle menber
> Add userHandle to WebAuthnAuthenticationContext

- gradle.properties
> Start 0.10.0 development

- webauthn4j-core/src/main/java/com/webauthn4j/validator/DefaultMaliciousCounterValueHandler.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/MaliciousCounterValueHandler.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/DefaultMaliciousCounterValueHandlerTest.java
Cont. to #183 
As `WebAuthnAuthenticationContext` is deprecated, replaced it with `AuthenticationObject`
> Change malicious counter value handler signature

- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialDescriptor.java
to PublickeyCredentialDescriptor as it is a member of CTAP interface
> Add Jackson annotation

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/FidoMdsMetadataItemsProvider.java
- webauthn4j-metadata/src/test/java/com/webauthn4j/metadata/FidoMdsMetadataItemsProviderTest.java
> Add token parameter

- build.gradle
- helper.gradle
Addresses https://github.com/webauthn4j/webauthn4j/issues/215
Add bintrayGpgSign and bintrayMavenCentralSync to retry to recover gpg sigining loss or maven central sync timeout.
> Add bintrayGpgSign and bintrayMavenCentralSync

- .github/workflows/ci.yml
- .github/workflows/pr-gate-ci.yml
- .github/workflows/release.yml
- .github/workflows/snapshot-release.yml
- build.gradle
- gradle.properties
- owasp/suppression.xml
Fixes #214 
add build property"failBuildOnCVSS" and set value on GitHub Action
workflow
> Make OWASP plugin build failed only on CI

- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnRegistrationManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/AttestationType.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/PackedAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/TPMAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/TPMIAlgPublic.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AttestationValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/ecdaa/DefaultECDAATrustworthinessValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/ecdaa/ECDAATrustworthinessValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/ecdaa/NullECDAATrustworthinessValidator.java
> Deprecate ECDAA

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorImplTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorTest.java
> Redesign Extensions (cont.)

- webauthn4j-core/src/main/java/com/webauthn4j/data/internal/MessageDigestAlgorithm.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/internal/SignatureAlgorithm.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AssertionSignatureValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/AbstractStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/internal/MessageDigestAlgorithmTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/internal/SignatureAlgorithmTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/TPMAuthenticator.java
as it is not intended for public use
> Move SignatureAlgorithm class under internal package

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/CoreAuthenticationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/CoreRegistrationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/RegistrationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticatorExtensionValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/ClientExtensionValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/CoreAuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/CoreRegistrationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticatorExtensionValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/BeanAssertUtilTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/ClientExtensionValidatorTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/AndroidKeyAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/AndroidSafetyNetAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/CustomAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/CustomRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/FIDOU2FAuthenticatorAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/FIDOU2FAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/TPMAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/UserVerifyingAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
Remove expectedExtensionIds member, which was deprecated in https://github.com/webauthn4j/webauthn4j/pull/330
> Remove expectedExtensionIds member

- webauthn4j-core/src/main/java/com/webauthn4j/data/client/Origin.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/OriginTest.java
* normalize Origin scheme and host by lowercasing them internally
* set Origin schemeSpecificPart value for http/https
> normalize Origin scheme and host & assign schemeSpecificPart value for http/https

- webauthn4j-core/build.gradle
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/Origin.java
- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/BeanAssertUtil.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/OriginValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/CollectedClientDataConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/OriginTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/server/ServerPropertyTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/ChallengeValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/OriginValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RpIdHashValidatorTest.java
This pull-request includes the commit from #353, and adds some follow-up commits.
> Relax origin scheme requirement

- webauthn4j-core/src/main/java/com/webauthn4j/data/client/Origin.java
- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/BeanAssertUtil.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/OriginValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/CollectedClientDataConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/OriginTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/server/ServerPropertyTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/ChallengeValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/OriginValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RpIdHashValidatorTest.java
* have Origin class to accept apk-hash-key and apk-hash-key-sha256 scheme
* allow multiple Origin objects associated with the ServerProperty
> support fido2 api for android  Origin and support validation against multiple origins

- webauthn4j-core/src/main/java/com/webauthn4j/data/AbstractImmutableMap.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialEntity.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/SingleValueExtensionBase.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/SingleValueExtensionInputBase.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/SingleValueExtensionOutputBase.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/AbstractStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/exception/ValidationException.java
Make abstract class constructor protected
> Polish code

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticationData.java
as it is marked as non-null by mistake
> Make AuthenticationData member nullable

- gradle.properties
as breaking changes are already introduced in current development version
> Switch next version to 0.15.0

- .github/workflows/snapshot-release.yml
- .travis.yml
Reverts webauthn4j/webauthn4j#405 as it doesn't work
> Revert "Move snapshot release task to Travis-CI"

- .github/workflows/release.yml
- .github/workflows/snapshot-release.yml
- README.md
- build.gradle
- docs/src/reference/asciidoc/en/introduction.adoc
- docs/src/reference/asciidoc/ja/introduction.adoc
and implement Maven Central direct publish task
> Remove bintray dependency as it shutdowns

- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialEntity.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialRpEntity.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialUserEntity.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/Origin.java
- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/PublicKeyCredentialRpEntityTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/PublicKeyCredentialUserEntityTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/OriginTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/server/ServerPropertyTest.java
- webauthn4j-util/src/main/java/com/webauthn4j/util/SignatureUtil.java
- webauthn4j-util/src/test/java/com/webauthn4j/util/SignatureUtilTest.java
Remove code deprecated in previous releases.
> Remove deprecated code

- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RegistrationDataValidatorTest.java
customRegistrationValidators was never set in the constructor.
> Initialized customRegistrationValidators in contructor

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/AggregatingMetadataItemsProvider.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/AggregatingMetadataStatementsProvider.java
- webauthn4j-metadata/src/test/java/com/webauthn4j/metadata/AggregatingMetadataItemsProviderTest.java
- webauthn4j-metadata/src/test/java/com/webauthn4j/metadata/AggregatingMetadataStatementsProviderTest.java
> Bugfix: Exception thrown when overlapping entries are returned

- webauthn4j-core/src/main/java/com/webauthn4j/anchor/SimpleTrustAnchorsProvider.java
- webauthn4j-core/src/test/java/com/webauthn4j/anchor/SimpleTrustAnchorsProviderTest.java
for straightforward use-case
Fixes #456
> Add SimpleTrustAnchorsProvider

- webauthn4j-core/src/main/java/com/webauthn4j/data/MessageDigestAlgorithm.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/SignatureAlgorithm.java
- MessageDigestAlgorithm
- SignatureAlgorithm
> Make algorithm classes serializable

- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnAuthenticationManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/ClientDataType.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/ClientDataTypeTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticationDataValidatorTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/FIDOU2FAuthenticatorAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/UserVerifyingAuthenticatorAuthenticationValidationTest.java
#539 + minor correction (38879ad)
> payment.get support

- build.gradle
to make it dependabot friendly
> Define dependency versions individually

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnCBORModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/CredentialProtectionPolicyByteDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/AbstractCtapCanonicalCborSerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/AuthenticationExtensionsAuthenticatorInputsSerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/AuthenticationExtensionsAuthenticatorOutputsSerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/AuthenticationExtensionsAuthenticatorInputs.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/extension/authenticator/AuthenticationExtensionsAuthenticatorInputsTest.java
To conform CTAP2 canonical CBOR encoding form, authenticator extension
serialization is updated
> Correct authenticator extension serialization

- docs/src/reference/asciidoc/en/deep-dive.adoc
- docs/src/reference/asciidoc/ja/deep-dive.adoc
Addressed https://github.com/webauthn4j/webauthn4j/pull/350#discussion_r754563001
> Correct typos in deep-dive.adoc

- docs/src/reference/asciidoc/ja/deep-dive.adoc
Nice to meet you. Thank you for your wonderful work.
By the way, when I read the document (I'm Japanese), there was something wrong with the description, and I thought it was incorrect, so I presented a correction plan.
We apologize for the inconvenience, but thank you for your understanding.
Best regards,
> Correct the description error in the Japanese translation

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorSelectionCriteria.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialCreationOptions.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialDescriptor.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialRequestOptions.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/CollectedClientData.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/TokenBinding.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorSelectionCriteriaTest.java
This pull request addresses #615 reported by @lajos-kiss, and is a follow up for #616
> Bugfix: equals method of container classes are broken by #574

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorSelectionCriteria.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorSelectionCriteriaTest.java
> Fixing broken equals() method of AuthenticatorSelectionCriteria

- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticatorDataConverter.java
Fixes https://github.com/webauthn4j/webauthn4j/issues/674
> Address NoSuchMethodError issue when using ByteBuffer in AuthenticatorDataConverter

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorTransport.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorTransportTest.java
Add support for "hybrid" authenticator transport (W3C Spec: https://github.com/w3c/webauthn/pull/1755)
> Add "hybrid" AuthenticatorTransport

- build.gradle
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnAuthenticationManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnRegistrationManager.java
- webauthn4j-core/src/test/resources/logback-test.xml
> Add trace logs for parser inputs and validator inputs

- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/DefaultTPMDevicePropertyDecoder.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMDevicePropertyDecoder.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/tpm/DefaultTPMDevicePropertyDecoderTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidatorTest.java
to make room to customize how to decode TPMDeviceProperty from subject alternative name
> WIP: introduce TPMDevicePropertyDecoder

- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/u2f/FIDOU2FAuthenticator.java
> Address NoSuchMethodError issue when using FIDOU2FAuthenticator with JDK8

- build.gradle
Reverts webauthn4j/webauthn4j#749
> Revert "Bump org.sonarsource.scanner.gradle:sonarqube-gradle-plugin from 3.5.0.2730 to 4.0.0.2929"

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/data/statement/AuthenticatorGetInfo.java
This will resolve an issue with Serialization/ Deserialization when only some of the options are present. Discussion post here: https://github.com/webauthn4j/webauthn4j/discussions/797
> Adding nullable to Options inside AuthenticatorGetInfo

- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
> Fixed typo in RegistrationDataValidator.java

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnCBORModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/cbor/NoneAttestationStatementSerializer.java
to serialize with CTAP2 canonical CBOR encoding form
> Add NoneAttestationStatementSerializer

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnCBORModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/cbor/AttestationObjectSerializer.java
to serialize with CTAP2 canonical CBOR encoding form
> Add AttestationObjectSerializer

- webauthn4j-test/src/main/java/com/webauthn4j/test/EmulatorUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/NoneAttestationAuthenticator.java
Resolves https://github.com/webauthn4j/webauthn4j/issues/851
> Implement none attestation authenticator

- build.gradle
Since year 2024 is comming, drop JDK8 support
> Drop JDK8 support

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/CompoundAttestationStatement.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/CompoundAttestationStatementTest.java
Note: Validator for CompoundAttestationStatement is not yet added
> Add CompoundAttestationStatement

- docs/src/reference/asciidoc/en/deep-dive.adoc
- docs/src/reference/asciidoc/ja/deep-dive.adoc
> Correct AttestationStatement serialization docs

- .github/workflows/ci.yml
- .github/workflows/pr-gate-ci.yml
to address changes introduced by recent sonar update
> Update sonr build option

- docs/src/reference/asciidoc/en/introduction.adoc
- docs/src/reference/asciidoc/ja/introduction.adoc
Update the reference document regarding the current supported JDK version
> Follow up JDK8 drop

- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/test/java/com/webauthn4j/server/ServerPropertyTest.java
Since tokenBinding is not supported by all current browsers
> Add tokenBindingId less constructors to ServerProperty

- README.md
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
to demonstrate how to use parseRegisrationResponseJSON and parseAuthenticationResponseJSON
> Update sample code in README

- github-release-notes-generator.yml
> Update release note generator config

- webauthn4j-core-async/build.gradle
- webauthn4j-core/build.gradle
- webauthn4j-device-check/build.gradle
- webauthn4j-metadata-async/build.gradle
- webauthn4j-metadata/build.gradle
- webauthn4j-test/build.gradle
- webauthn4j-util/build.gradle
Addresses https://github.com/webauthn4j/webauthn4j/issues/987
> Add Automatic-Module-Name entry to MANIFEST.MF

- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
... by adding a comma before the next field
> align ServerProperty's toString() to other toString() implementations

- build.gradle
- webauthn4j-core-async/build.gradle
- webauthn4j-core-async/src/main/java/module-info.java
- webauthn4j-core/build.gradle
- webauthn4j-core/src/main/java/module-info.java
- webauthn4j-device-check/build.gradle
- webauthn4j-device-check/src/main/java/module-info.java
- webauthn4j-metadata-async/build.gradle
- webauthn4j-metadata-async/src/main/java/module-info.java
- webauthn4j-metadata/build.gradle
- webauthn4j-metadata/src/main/java/module-info.java
- webauthn4j-test/build.gradle
- webauthn4j-test/src/main/java/com/webauthn4j/test/AttestationCertificateBuilder.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestAttestationUtil.java
- webauthn4j-test/src/main/java/module-info.java
- webauthn4j-util/build.gradle
- webauthn4j-util/src/main/java/module-info.java
Addresses https://github.com/webauthn4j/webauthn4j/issues/989
- Exports all packages except internal ones
> Add explicit java module support

- build.gradle.kts
Enable jacoco xml test report again
> Follow up : build.gradle rewrite

- docs/src/reference/asciidoc/en/quick-start.adoc
Update `ValidationException` to `VerificationException`
>   Update ValidationException to VerificationException

- webauthn4j-core-async/src/main/java/module-info.java
As some packages are not included by mistake
> Correct webauthn4j-core-async module-info

- webauthn4j-appattest/build.gradle.kts
- webauthn4j-appattest/src/main/java/module-info.java
- webauthn4j-core-async/build.gradle.kts
- webauthn4j-core/build.gradle.kts
- webauthn4j-core/src/main/java/module-info.java
- webauthn4j-metadata-async/build.gradle.kts
- webauthn4j-metadata/build.gradle.kts
- webauthn4j-metadata/src/main/java/module-info.java
- webauthn4j-test/build.gradle.kts
- webauthn4j-test/src/main/java/module-info.java
as it is exposed to JsonConverter and CborConverter API surface
> Mark jackson transitive dependency

- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/HMACGetSecretInput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/HMACGetSecretOutput.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientOutputsConverterTest.java
> Bugfix: Deserialization issue with HMACGetSecretInput and HMACGetSecretOutput

- README.md
OpenUnison has been using WebAuthn4j for a couple of years now.  our largest implementation has over 10k passkeys registered!
> Update README.md with OpenUnison as a service that uses webauthn4j

- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredential.java
Please use `PublicKeyCredential#getResponse` instead
> Remove deprecated PublicKeyCredential#getAuthenticatorResponse

- webauthn4j-core-async/src/main/java/com/webauthn4j/async/verifier/AuthenticationDataAsyncVerifier.java
- webauthn4j-core-async/src/main/java/com/webauthn4j/async/verifier/RegistrationDataAsyncVerifier.java
- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/main/java/com/webauthn4j/verifier/AuthenticationDataVerifier.java
- webauthn4j-core/src/main/java/com/webauthn4j/verifier/RegistrationDataVerifier.java
- webauthn4j-core/src/main/java/com/webauthn4j/verifier/internal/TokenBindingVerifier.java
as it is removed from WebAuthn Level.3
> Deprecate token binding support

- docs/src/reference/asciidoc/en/faq.adoc
- docs/src/reference/asciidoc/ja/faq.adoc
> Document allowCredentials and excludeCredentials

- build.gradle.kts
> Suppress JPMS warning regarding 'exports to' directive
