webauthn4j/webauthn4j

- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticatorTransportConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/WebAuthnRegistrationContext.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnRegistrationContextValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/WebAuthnRegistrationContextTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticatorTransportConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorAttestationResponseTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/WebAuthnRegistrationContextTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/BeanAssertUtilTest.java
- webauthn4j-core/src/test/java/integration/component/NullAttestationStatementValidatorTest.java
- webauthn4j-core/src/test/java/integration/scenario/CustomRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/FIDOU2FAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/UserVerifyingAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/sample/Sample.java
Since `WebAuthnRegistrationContext` is an input envelope class for validator, it's field should not be specialized type to leave the validator input check task
> Make WebAuthnRegistrationContext transports String set

- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidatorTest.java
The TPMAttestationValidator.validateSubjectAlternativeName triggered a NullPointerException on line 263:
```
byte[] manufacturerAttr = (byte[]) directoryName.getRdns().get(0).toAttributes().get("2.23.133.2.1").get();
byte[] partNumberAttr = (byte[]) directoryName.getRdns().get(0).toAttributes().get("2.23.133.2.2").get();
byte[] firmwareVersionAttr = (byte[]) directoryName.getRdns().get(0).toAttributes().get("2.23.133.2.3").get();
````
The .getRdns() returns List<Rdns>, so moving it to index 0 always returns the same. The get("...") on the attributes failed on 2.23.133.2.2 because it did not exist.
Refactored it to
```
Map<String, Object> map = directoryName.getRdns().stream()
.map(Rdn::toAttributes) //Stream<Attributes>
.map(this::toKeyValue) //Steam<KeyValue>
.flatMap(Collection::stream) …
```
> TPMAttestationValidator validateSubjectAlternativeName bug

- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/u2f/FIDOU2FAuthenticator.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnModelAuthenticator.java
- webauthn4j-util/src/main/java/com/webauthn4j/util/KeyUtil.java
* Stop using `SecureRandom.getInstanceStrong()` as it makes large overhead, and I don't see value on using it
* Have `SecureRandom` per classes to reduce instance creation overhead.
> Improve SecureRandom handling

- build.gradle
- gradle.properties
- owasp/suppression.xml
- webauthn4j-core/build.gradle
- webauthn4j-metadata/build.gradle
- webauthn4j-test/build.gradle
- webauthn4j-util/build.gradle
As the vulnerbility does not affect WebAuthn4J directly,
this issue is not marked as bug.
> Bump Jackson version to 2.9.9.3

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/AttestationObject.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AbstractCOSEKey.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AttestedCredentialData.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AuthenticatorData.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/AndroidKeyAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifier.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/SignatureAlgorithm.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/TPMAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AssertionSignatureValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/AbstractStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidkey/AndroidKeyAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/packed/PackedAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/tpm/TPMAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/EC2COSEKeyTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/ESSignatureAlgorithmTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/COSEAlgorithmIdentifierTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/SignatureAlgorithmTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/AbstractStatementValidatorTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/AndroidKeyAuthenticator.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/PackedAuthenticator.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/TPMAuthenticator.java
as COSE algorithms are not limited to signature algorithms, `jcaName` and `messageDigestJcaName` are moved to `SignatureAlgorithm` class.
> Redesign COSEAlgorithmIdentifier class

- webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnRegistrationContextValidator.java
in createNonStrictRegistrationContextValidator
> Bugfix: NullTPMAttestationStatementValidator is not included

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/FidoMdsMetadataValidator.java
As `FidoMdsMetadataValidator` is hard to initialize, add easy constructors that covers most use cases.
> Improve FidoMdsMetadataValidator constructors

- webauthn4j-core/src/main/java/com/webauthn4j/converter/util/CborConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/util/JsonConverter.java
as it wil become package private in 0.11.0 release.
User need to get `JsonConverter` or `CborConverter` instance from `ObjectConverter` instance.
> Deprecates JsonConverter and CborConverter constructors

- README.md
- docs/src/reference/asciidoc/en/quick-start.adoc
- docs/src/reference/asciidoc/ja/quick-start.adoc
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
- webauthn4j-core/src/test/java/sample/WebAuthnRegistrationContextValidatorSample.java
Fix documentation - use credentialId from authenticationData instead of attestedCredentialData in authentication flow
As per specification "For assertion signatures, the AT flag MUST NOT be set and the attestedCredentialData MUST NOT be included."
https://www.w3.org/TR/webauthn-2/#sctn-authenticator-data
> Fix documentation - use credentialId from authenticationData in authentication

- build.gradle
- webauthn4j-core/build.gradle
- webauthn4j-metadata/build.gradle
- webauthn4j-test/build.gradle
- webauthn4j-util/build.gradle
by using gradle api/implementation dependency definition.
Now the transitive dependencies are not exposed to the library user.
These transitive dependencies are removed:
- `org.slf4j:slf4j-api`
- `org.apache.kerby:kerby-asn1`
- `com.fasterxml.jackson.core:jackson-databind`
- `com.fasterxml.jackson.dataformat:jackson-dataformat-cbor`
- `com.fasterxml.jackson.datatype:jackson-datatype-jsr310`
> Reduce dependencies exposure

- gradle/wrapper/gradle-wrapper.properties
This reverts commit 3a624bd940387d502b117baea65a507792203085.
As the commit broke `master` branch
> Revert "Update gradle to 6.3"

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnCBORModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnJSONModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/ExtensionAuthenticatorOutputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/ExtensionClientInputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/ExtensionClientOutputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionAuthenticatorOutputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionClientInputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionClientOutputDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/UnknownExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/UnknownExtensionClientInput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/UnknownExtensionClientOutput.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionAuthenticatorOutputDeserializerTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionClientInputDeserializerTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/jackson/deserializer/UnknownExtensionClientOutputSerializerTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/extension/authenticator/UnknownExtensionAuthenticatorOutputTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/extension/client/UnknownExtensionClientInputTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/extension/client/UnknownExtensionClientOutputTest.java
- webauthn4j-util/src/main/java/com/webauthn4j/util/HexUtil.java
When an unknown extension is included in the serialized data, `DataConversionException` was thrown (https://github.com/webauthn4j/webauthn4j/blob/0.11.0.RELEASE/webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverterTest.java#L64-L68) while deserializing.
In W3C WebAuthn spec level1, it was requested to reject unintended extension (https://www.w3.org/TR/webauthn/#registering-a-new-credential), but in level2 spec, rejecting unintended extension is left to relying party decision (https://www.w3.org/TR/2019/WD-webauthn-2-20191126/#sctn-registering-a-new-credential).
Since rejecting unknown extension is not welcomed ( https://github.com/webauthn4j/webauthn4j/issues/260 ), this PR changes the behavior.
Now `DataConversionException` won't be thrown …
> Align unknown extension handling to WebAuthn Level2 draft1

- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/u2f/FIDOU2FAttestationStatementValidator.java
As U2F signature is not calculated over autenticatorData and
clientDataHash, message is corrected.
> Correct FIDO U2F signature varidation error message

- build.gradle
Since WebAuthn4J uses dependencyManagement (BOM) feature to define its
dependency versions, each dependency definition doesn't define version.
As a consequence, POM file for WebAuthn4J doesn't contain dependency
version in dependencies.dependency.version element, and it cause
error in the library concumer environment.
This commit fixes it by using Gradle publish dependencies "Resolved versions"
strategy.
> Expose dependency version at dependencies.dependency.version in POM file

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorSelectionCriteria.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/ResidentKeyRequirement.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticatorSelectionCriteriaTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/ResidentKeyRequirementTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnAuthenticatorAdaptor.java
New enum `ResidentKeyRequirement` is introduced from WebAuthn Level2 WD1, which is used in `AuthenticatorSelectionCriteria`. This change reflect it.
https://www.w3.org/TR/2019/WD-webauthn-2-20191126/#sctn-credential-storage-modality
This PR addresses #268
> Add ResidentKeyRequirement enum

- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/CredentialPropertiesExtensionClientOutput.java
As credProps is a registration extension, CredentialPropertiesExtensionClientOutput must implement RegistrationExtensionClientOutput
> Bugfix: CredentialPropertiesExtensionClientOutput

- build.gradle
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/AuthenticationExtensionsSupported.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/Coordinates.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/GenericTransactionAuthorizationExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/LocationExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/SimpleTransactionAuthorizationExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/SupportedExtensionsExtensionAuthenticatorInput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/SupportedExtensionsExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/authenticator/UserVerificationIndexExtensionAuthenticatorOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/AuthenticatorSelectionExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/BiometricAuthenticatorPerformanceBoundsExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/GenericTransactionAuthorizationExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/LocationExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/SimpleTransactionAuthorizationExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/SupportedExtensionsExtensionClientInput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/SupportedExtensionsExtensionClientOutput.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/extension/client/UserVerificationIndexExtensionClientOutput.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticatorDataConverterTest.java
Extensions unimplemented by client platforms(browsers) are removed from WebAuthn Level2 spec.
This commit reflect the change.
Deprecated extensions will be removed in 0.13.0.RELEASE.
> Deprecate removed extensions

- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnAuthenticationManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnRegistrationManager.java
- webauthn4j-core/src/test/java/com/webauthn4j/WebAuthnAuthenticationManagerTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/WebAuthnRegistrationManagerTest.java
`WebAuthnManager` is intended that its instance is shared between registration phase and authentication phase to keep configuration consistency easily. 
But in some use-cases, sharing its instance between two phases are not straight-forward and restricts application design, this pull-request splits `WebAuthnManager` into `WebAuthnRegistrationManager` and `WebAuthnAuthenticationManager` and delegates processing to these classes.
With this change Validator for authentication phase can be initialized
without attestation statement validation configuration.
> Split WebAuthnManager

- build.gradle
- webauthn4j-core/build.gradle
- webauthn4j-metadata/build.gradle
- webauthn4j-test/build.gradle
- webauthn4j-util/build.gradle
To define dependency version, constraints block need to be used.
This commit corrects inappropriate definitions.
> Define dependency version in a proper way

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/RegistrationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/BeanAssertUtilTest.java
- webauthn4j-core/src/test/java/integration/scenario/AndroidKeyAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/AndroidSafetyNetAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/CustomAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/CustomRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/FIDOU2FAuthenticatorAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/FIDOU2FAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/TPMAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/UserVerifyingAuthenticatorRegistrationValidationTest.java
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
from Parameters classes
As matching extension id(s) and expected list is no longer required from
WebAuthn Level 2 spec, deprecate the feature.
The feature will be removed by WebAuthn4J 1.0 GA release.
> Deprecate expectedExtensionIds member

- webauthn4j-core/src/main/java/com/webauthn4j/validator/AttestationValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/CoreRegistrationObject.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationObject.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/AndroidSafetyNetAttestationStatementValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/certpath/CertPathTrustworthinessValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/certpath/CertPathTrustworthinessValidatorBase.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/trustworthiness/certpath/NullCertPathTrustworthinessValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RegistrationObjectTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestDataUtil.java
* Use Instant class instread of LocalDateTime class in RegistrationObject.timestamp
* CertPathTrustworthinessValidator.validate takes timestamp as the 3rd argument.
Breaking change:
* `validate(AAGUID aaguid, CertificateBaseAttestationStatement attestationStatement)` method in `CertPathTrustworthinessValidator` interface is changed to `validate(AAGUID aaguid, CertificateBaseAttestationStatement attestationStatement, Instant timestamp)`.
> Redesign registration timestamp handling

- webauthn4j-core/src/main/java/com/webauthn4j/converter/AttestationObjectConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticationExtensionsClientOutputsConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticatorTransportConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/CollectedClientDataConverter.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AttestationObjectConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientOutputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticatorTransportConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/CollectedClientDataConverterTest.java
to make its behavior consistent and Kotlin friendly.
**Breaking Change**
- If you have passed null value to converter and expected null value is to be returned, you need to rewrite your caller code to do null check and return null value by yourself.
Sorry for inconvenience, but it is for making converter arguments and return values non-nullable and make it consistent.
> Redesign Converters not to pass through null value

- webauthn4j-core/src/main/java/com/webauthn4j/server/CoreServerProperty.java
- webauthn4j-core/src/main/java/com/webauthn4j/server/ServerProperty.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/RegistrationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/server/ServerPropertyTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/ChallengeValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RpIdHashValidatorTest.java
* Refine `ServerProperty` nullability as `Challenge` can be null when the challenge is expired or not stored
* Remove `getOrigin` as it is already deprecated in a previous release
> Refine ServerProperty nullability and remove getOrigin method

- webauthn4j-core/src/main/java/com/webauthn4j/data/CoreAuthenticationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/CoreRegistrationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/BeanAssertUtil.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/ChallengeValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/CoreAuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/CoreRegistrationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/RegistrationDataTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/BeanAssertUtilTest.java
As RegistrationParameters and AuthenticationParameters class members are marked as non-null, move non-null check logic from BeanAssertUtil to these class constructors
> Move Parameters classes non-null check into these classes

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorSelectionCriteria.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnAuthenticatorAdaptor.java
to represent input precisely
**Breaking Change**
- AuthenticatorSelectionCriteria#isRequireResidentKey() now returns null
> Make AuthenticatorSelectionCriteria.requireResidentKey nullable

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/AndroidSafetyNetAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/Response.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/jws/JWSException.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/AndroidSafetyNetAttestationStatementValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/AndroidSafetyNetAttestationStatementValidatorTest.java
to deserialize data precisely
**Breaking Changes**
- `ctsProfileMatch` is changed from boolean to Boolean
- `basicIntegrityis` changed from boolean to Boolean
- `isCtsProfileMatch` is renamed to `getCtsProfileMatch`
- `isBasicIntegrity` is renamed to `getBasicIntegrity`
> Make AndroidSafetyNetAttestationStatement Response members nullable

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnJSONModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/JWSHeaderDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/JWSHeaderSerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/statement/AndroidSafetyNetAttestationStatement.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/jws/JWS.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/jws/JWSHeader.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/jws/JWSFactoryTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/jws/JWSHeaderTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/attestation/statement/androidsafetynet/AndroidSafetyNetAttestationStatementValidatorTest.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/FidoMdsMetadataItemsProvider.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/AndroidSafetyNetAuthenticator.java
**Breaking change**
* JWSHeader.x5c type is changed from `AttestationCertificatePath` to `CertPath` because it is not always attestation certificates
> Redesign JWS classes

- build.gradle
Reverts webauthn4j/webauthn4j#393 as it breaks snapshot release
> Revert "Bump spring-boot-dependencies from 2.3.5.RELEASE to 2.4.0"

- build.gradle
This reverts commit d074dd727708e6ae344d748057c405a5b211be86 as it
breaks build
> Revert "Bump build-info-extractor-gradle from 4.17.2 to 4.18.0"

- build.gradle
Reverts webauthn4j/webauthn4j#396 as it turned out that spring boot BOM doesn't break the build.
> Revert "Revert "Bump spring-boot-dependencies from 2.3.5.RELEASE to 2.4.0""

- webauthn4j-util/build.gradle
because actually, bcprov-jdk15on and bcpkix-jdk15on are only used by webauthn4j-test.
> Remove BouncyCastle from webauthn4j-util dependency

- webauthn4j-core/src/main/java/com/webauthn4j/converter/AttestationObjectConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AttestedCredentialDataConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticationExtensionsClientOutputsConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticatorDataConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/AuthenticatorTransportConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/CollectedClientDataConverter.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AttestationObjectConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AttestedCredentialDataConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientInputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticationExtensionsClientOutputsConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/AuthenticatorTransportConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/CollectedClientDataConverterTest.java
Make converters to throw `DataConversionException` instead of `IllegalArgumentException` when null check failed
> Make converters to throw DataConversionException when null check failed

- docs/src/reference/asciidoc/en/deep-dive.adoc
- docs/src/reference/asciidoc/ja/deep-dive.adoc
- webauthn4j-device-check/src/main/java/com/webauthn4j/appattest/DeviceCheckManager.java
This pull-request makes `DeviceCheckManager.createObjectConverter` public.
Users of `webauthn4j-device-check` needs a `ObjectConverter` instance with a `DeviceCheckCBORModule`, and this helper method satisfies these needs.
This fixes #418
> Make DeviceCheckManager.createObjectConverter public

- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/OriginValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/OriginValidatorImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticationDataValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/OriginValidatorImplTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/RegistrationDataValidatorTest.java
- webauthn4j-core/src/test/java/integration/component/CustomOriginValidatorTest.java
In some cases, users want to customize OriginValidator logic.
This commit make OriginValidator to interface and expose it to public.
Now users can set their own OriginValidator implementation to
RegistrationDataValidator or AuthenticationDataValidator through their
setter.
> Expose OriginValidator to public

- gradle.properties
Change next version from 0.15.2 to 0.16.0 as we will have breaking change (remove deprecated code #484).
> Start 0.16.0 development

- webauthn4j-test/src/main/java/com/webauthn4j/test/CipherUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestDataUtil.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/PublicKeyCredentialSource.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnModelAuthenticator.java
- webauthn4j-test/src/test/java/com/webauthn4j/test/authenticator/webauthn/PackedAuthenticatorTest.java
I was using the PackedAuthenticator today to do an integration test against a new service and ran into a few of bugs.
- COSEAlgorithmIdentifier is not an enum, so it needs a `.equals()` check instead of `==` (this comes up when it's deserialized JSON, which for me came up since I was deserializing options returned in a REST request from my service under test).
- Jackson wasn't able to serialize the PrivateKey in the `PublicKeyCredentialSource` so I switched this to a COSEKey instead.
- CipherUtil wasn't able to encrypt/decrypt the serialized credential since the attestion key was EC and not RSA, so I switched this to AES.
I added a couple of test cases that cover these things.
> Fix bugs using non-resident keys in WebAuthnModelAuthenticator.

- webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/WebAuthnModelAuthenticator.java
- webauthn4j-test/src/test/java/com/webauthn4j/test/authenticator/webauthn/PackedAuthenticatorTest.java
Fixing one more follow-up bug I found related to my previous PR (#510). When looking up a key the credential ID should get set on the result (since it's not part of what got serialized when it was created). Otherwise the credential ID ends up being missing on the GetAssertionResponse.
> Fix missing credenital id from assertion of non-resident credential.

- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnAuthenticationManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/WebAuthnManager.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/client/ClientDataType.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/RegistrationDataValidator.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/client/ClientDataTypeTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/FIDOU2FAuthenticatorAuthenticationValidationTest.java
- webauthn4j-core/src/test/java/integration/scenario/webauthn/UserVerifyingAuthenticatorAuthenticationValidationTest.java
Hello, I would like to validate credentials created using [secure payment confirmation (SPC)](https://w3c.github.io/secure-payment-confirmation/) using this library.
SPC is a Web API to support streamlined authentication during a payment transaction and is built on top of Webauthn standards. One of the differences is that the `type` of the returned `clientDataJSON` is `payment.create` during enrollment and `payment.get` during authentication. This pull request adds those two types as valid `ClientDataType` values.
> WIP: add SPC ClientDataType (payment.get)

- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/CoreAuthenticatorImpl.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/CoreAuthenticatorImplTest.java
`CoreAuthenticatorImpl`#`getAttestationStatement` (and `AuthenticatorImpl`, which inherits `CoreAuthenticatorImpl` ) must be nullable because `CoreAuthenticator`#`getAttestationStatement` is nullable.
> Bugfix: CoreAuthenticatorImpl#getAttestationStatement must be nullable

- webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/AuthenticatorData.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/authenticator/AuthenticatorDataTest.java
As per the documentation https://w3c.github.io/webauthn/#authenticator-data , there are two additional flags available in authData to indicate backupEligbility and backupState for the authenticators. The flags essentially help us to resolve if an authenticator is a multi-device credential and has the credentials backedup. This change exposes the method to read the bits for the BE and BS flags.
> add support for additional BE and BS flags

- README.md
- docs/src/reference/asciidoc/en/quick-start.adoc
- docs/src/reference/asciidoc/ja/quick-start.adoc
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
RegistrationParameters's constructor accepts expectedExtensionIds is removed at https://github.com/webauthn4j/webauthn4j/pull/344/files#diff-abcde77c9698cbdec05c5532218a2cad603868308f22302eb6026a35eb1a2a8bL36
> Remove expectedExtensionIds from quickstart and sample code

- webauthn4j-util/src/main/java/com/webauthn4j/util/HKDFUtil.java
Please note HKDFUtil.calculateHKDFSHA256 is not used from anywhere else in webauthn4j. If your application didn't use HKDFUtil.calculateHKDFSHA256 directly, it doesn't affect your application
> Bugfix: HKDFUtil.calculateHKDFSHA256

- docs/src/reference/asciidoc/en/deep-dive.adoc
- docs/src/reference/asciidoc/en/quick-start.adoc
- docs/src/reference/asciidoc/ja/deep-dive.adoc
- docs/src/reference/asciidoc/ja/quick-start.adoc
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/Authenticator.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/AuthenticatorImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/CoreAuthenticator.java
- webauthn4j-core/src/main/java/com/webauthn4j/authenticator/CoreAuthenticatorImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/credential/CoreCredentialRecord.java
- webauthn4j-core/src/main/java/com/webauthn4j/credential/CoreCredentialRecordImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/credential/CredentialRecord.java
- webauthn4j-core/src/main/java/com/webauthn4j/credential/CredentialRecordImpl.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/AuthenticationDataValidator.java
- webauthn4j-core/src/main/java/com/webauthn4j/validator/exception/BadBackupEligibleFlagException.java
- webauthn4j-core/src/test/java/com/webauthn4j/credential/CoreCredentialRecordImplTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/credential/CredentialRecordImplTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/AuthenticationDataValidatorTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/validator/exception/BadBackupEligibleFlagExceptionTest.java
- webauthn4j-core/src/test/java/sample/WebAuthnManagerSample.java
- webauthn4j-device-check/src/main/java/com/webauthn4j/appattest/authenticator/DCAppleDevice.java
- webauthn4j-device-check/src/main/java/com/webauthn4j/appattest/authenticator/DCAppleDeviceImpl.java
New `CredentialRecord` interface and `CoreCredentialRecord` interface are introduced.
To represent Passkeys credentials, these interfaces have additional methods in addition to the legacy `Authenticator` and `CoreAuthenticator` interface.
**Breaking change**
* `Authenticator` interface and `CoreAuthenticator` interface which represent a legacy webauthn credential are now deprecated
* Since these `Authenticator` interfaces will be removed in the future version, please update your concrete classes to implement the `CredentialRecord` interface instead of the `Authenticator` interface.
> Align AuthenticationDataValidator logic to WebAuthn Level3 working draft1

- build.gradle
`http://www.apache.org/license/LICENSE-2.0.txt` returns 404, the correct link is `https://www.apache.org/licenses/LICENSE-2.0.txt`
> Fix URL for Apache license

- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/ByteArrayBase64ConverterModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/WebAuthnJSONModule.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/json/ByteArrayBase64Deserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/deserializer/json/ByteArrayBase64UrlDeserializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/json/ByteArrayBase64Serializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/jackson/serializer/json/ByteArrayBase64UrlSerializer.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/util/CborConverter.java
- webauthn4j-core/src/main/java/com/webauthn4j/converter/util/JsonConverter.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/jackson/ByteArrayBase64ConverterModuleTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/converter/util/JsonConverterTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/TPMGeneratedTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/TPMISTAttestTest.java
Since WebAuthn Level3 working draft uses base64url encoding for byte array encoding, we change the default byte array encoding method from base64 to base64url.
If you use WebAuthn4J for JSON serialization, you may be impacted by this breaking change.
You can still decode base64 encoded WebAuthn data types by registering `ByteArrayBase64ConverterModule` to your `JsonConverter` in this way:
```
ObjectConverter objectConverter = new ObjectConverter();
JsonConverter jsonConverter = objectConverter.getJsonConverter();
jsonConverter.registerModule(new ByteArrayBase64ConverterModule());
jsonConverter.readValue(sourceString, YourDTO.class);
```
> Change the default serialization method of byte arrays from Base64 to Base64Url

- webauthn4j-core/src/main/java/com/webauthn4j/data/PublicKeyCredentialRequestOptions.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/PublicKeyCredentialRequestOptionsTest.java
https://github.com/webauthn4j/webauthn4j/pull/956 added `PublicKeyCredentialCreationOptions.hints`, but `PublicKeyCredentialRequestOptions.hints` was left untouched. This pull-request adds `PublicKeyCredentialRequestOptions.hints`.
> Add PublicKeyCredentialRequestOptions.hints

- build.gradle.kts
Adresses #1042
From 0.28.0.RELEASE, target version configuration was dropped by mistake. This commit adds it again
> Set target version Java 11 again

- webauthn4j-appattest/src/main/java/module-info.java
- webauthn4j-core/src/main/java/module-info.java
- webauthn4j-metadata/src/main/java/module-info.java
Java9 module requires packages to be marked 'opens' to accept jackson serialization
> Opens data classes for reflection

- .github/dependabot.yml
as we no longer support 0.24.x
> Remove dependabot for 0.24.x branch

- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/FidoMDS3MetadataBLOBProvider.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/HttpClient.java
- webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/SimpleHttpClient.java
- webauthn4j-metadata/src/test/java/com/webauthn4j/metadata/FidoMDS3MetadataBLOBProviderTest.java
Redesign `HttpClient#fetch` to return `Response` instead of `String`. 
This only affects if you have implemented your own `HttpClient`. `HttpAsyncClient` is not affected.
> Redesign HttpClient to align with HttpAsyncClient

- webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticationParameters.java
- webauthn4j-core/src/main/java/com/webauthn4j/data/CoreAuthenticationParameters.java
- webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorImplTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/data/AuthenticationParametersTest.java
- webauthn4j-core/src/test/java/com/webauthn4j/verifier/AuthenticationObjectTest.java
- webauthn4j-test/src/main/java/com/webauthn4j/test/TestDataUtil.java
to guide library users to pass `CredentialRecord` as a parameter
> Deprecate AuthenticationParameters constructor that takes Authenticator as a parameter

- webauthn4j-core/src/main/java/com/webauthn4j/data/client/ClientDataType.java
Use `ClientDataType.WEBAUTHN_CREATE` and `ClientDataType.WEBAUTHN_GET` instead
> Remove deprecated ClientDataType.Create and ClientDataType.GET

- build.gradle.kts
as the workaround is no longer needed
> Polish build.gradle.kts
